### ISSUE TITLE
[Error: EACCES, Permission denied]

### ISSUE THREAD

**Issue by bguillard** [tim-hellhake/piface-adapter#1]
Hi, and thanks for the great work!
I however run into some trouble making piface-adapter work.
**Setup**
Raspberry Pi 1 B+, Raspbian Buster
PiFace 1
**Steps to reproduce**
 - Install WebThings via the official package [here](https://github.com/mozilla-iot/gateway-deb)
 - Install PiFace addon
 - Scan for things: it does not find the PiFace board, and here's what I see in WebThings logs:
```
piface-adapter: Loading add-on piface-adapter from /etc/webthings-gateway/addons/piface-adapter
piface-adapter: Unhandled Rejection
piface-adapter: { [Error: EACCES, Permission denied] errno: 13, code: 'EACCES', syscall: 'open' }
Opened a new things socket
About to call startPairing on PiFaceAdapter
piface-adapter: Adapter: PiFaceAdapter id PiFaceAdapter pairing started
Pairing timeout
piface-adapter: Adapter: PiFaceAdapter id PiFaceAdapter pairing cancelled
```

**Additional details**
_WebThings is working:_ The Weather plugin is working correctly.
_PiFace board is working:_ SPI is enabled (via raspi-config), and I can control the PiFace board using Python and ``pifacedigitalio``.
_Permission and ownership seem fine:_ in the ``/etc/webthings-gateway/addons/piface-adapter/`` directory:
```
drwxr-xr-x 4 webthings webthings  4096 .
drwxr-xr-x 4 webthings webthings  4096 ..
-rw-r--r-- 1 webthings webthings 16725 LICENSE
-rw-r--r-- 1 webthings webthings   711 README.md
-rw-r--r-- 1 webthings webthings 13496 SHA256SUMS
drwxr-xr-x 2 webthings webthings  4096 lib
-rw-r--r-- 1 webthings webthings   496 manifest.json
drwxr-xr-x 6 webthings webthings  4096 node_modules
-rw-r--r-- 1 webthings webthings   988 package.json
```

Many thanks in advance for your help, I can easily provide more info/logs if required.

**Comment by tim-hellhake** [comment]
Wow, thank you for the very well structured and detailed bug report!

> Hi, and thanks for the great work!

You're welcome!

I only tested it on the PiFace 2 but the SPI chip should be the same.

> { [Error: EACCES, Permission denied] errno: 13, code: 'EACCES', syscall: 'open' }

Looks like the addon cannot open the SPI device because of missing permissions.
Can you show me the output of `ls -l /dev/spi*`?

**Comment by bguillard** [comment]
Sure, this is what it reads:
```
crw-rw---- 1 root spi 153, 0 Apr 26 22:21 /dev/spidev0.0
crw-rw---- 1 root spi 153, 1 Apr 26 22:21 /dev/spidev0.1
```

As for PiFace 1 and 2, my understanding is that they are electronically identical indeed.

**Comment by bguillard** [comment]
Alright; you put me on the correct track to solve this: following pifacommon manual install guide from [here](http://piface.github.io/pifacecommon/installation.html), I added user webthing to group spi with
```
sudo gpasswd -a webthings spi
```
After rebooting PiFace is now detected by WebThings and seems to be working as it should. Many thanks!

**Comment by tim-hellhake** [comment]
Yeah, that's what I thought.
But I'm still not sure why I didn't have the problem.
I need to check this on a fresh gateway installation.

**Comment by tim-hellhake** [comment]
The issue should be resolved by https://github.com/WebThingsIO/gateway/pull/2519
